spring:
  application:
    name: mbad-project
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
  thymeleaf:
    cache: false
